# Generated by Django 5.2.7 on 2025-11-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1074_workflowrun_deleted_at_workflowrun_restored_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION sua_loai_van_ban_fn()
            RETURNS trigger AS $$
            DECLARE
                v_doc_type_name TEXT;
                v_field_id INTEGER;

                fields JSONB := '{
                    "Công văn đến": [
                        "Ngày đến",
                        "Số đến",
                        "Tác giả",
                        "Số, ký hiệu văn bản",
                        "Ngày tháng văn bản",
                        "Tên loại và trích yếu Nội dung văn bản",
                        "Người nhận",
                        "Ngày chuyển"
                    ],
                    "Công văn đi": [
                        "Số, ký hiệu văn bản",
                        "Ngày tháng văn bản",
                        "Tên loại và trích yếu Nội dung văn bản",
                        "Nơi nhận văn bản",
                        "Đơn vị, người nhận văn bản",
                        "Ngày chuyển"
                    ]
                }';
                v_fields TEXT[];
                v_field TEXT;
            BEGIN
                -- Chỉ thực thi khi thay đổi document_type_id
                IF NEW.document_type_id IS DISTINCT FROM OLD.document_type_id THEN
                    
                    -- Lấy name của document type
                    SELECT name INTO v_doc_type_name
                    FROM documents_documenttype
                    WHERE id = NEW.document_type_id;
                
                DELETE FROM documents_customfieldinstance WHERE document_id = NEW.id;

                v_fields := ARRAY( SELECT jsonb_array_elements_text(fields->v_doc_type_name) );

                    -- Lặp qua từng field trong mảng
                    FOREACH v_field IN ARRAY v_fields LOOP

                        -- Tìm field_id tương ứng
                        SELECT id INTO v_field_id
                        FROM documents_customfield
                        WHERE name = v_field
                        LIMIT 1;

                        -- Chỉ insert nếu field tồn tại và chưa có customfieldinstance
                        IF v_field_id IS NOT NULL THEN
                            
                            -- Kiểm tra tránh trùng
                            IF NOT EXISTS (
                                SELECT 1
                                FROM documents_customfieldinstance
                                WHERE document_id = NEW.id
                                AND field_id = v_field_id
                            ) THEN
                                INSERT INTO documents_customfieldinstance (created, document_id, field_id)
                                VALUES (NOW(), NEW.id, v_field_id);
                            END IF;

                        END IF;

                    END LOOP;

                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER sua_loai_van_ban
            AFTER UPDATE OF document_type_id ON documents_document
            FOR EACH ROW
            EXECUTE FUNCTION sua_loai_van_ban_fn();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS sua_loai_van_ban ON documents_document;
            DROP FUNCTION IF EXISTS sua_loai_van_ban_fn();
            """
        )
    ]
