# Generated by Django 5.2.7 on 2025-11-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1075_add_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION create_default_savedviews_for_user()
            RETURNS trigger AS $$
            DECLARE
                -- Tên các view sẽ được tạo
                v_names TEXT[] := ARRAY['Công văn đến', 'Công văn đi', 'Văn bản nội bộ'];

                v_name TEXT;
                v_savedview_id BIGINT;
                v_doc_type_id BIGINT;
            BEGIN
                FOREACH v_name IN ARRAY v_names LOOP

                    -- Lấy document_type_id tương ứng theo tên
                    SELECT id INTO v_doc_type_id
                    FROM documents_documenttype
                    WHERE name = v_name
                    LIMIT 1;

                    IF v_doc_type_id IS NULL THEN
                        RAISE NOTICE 'Không tìm thấy documenttype cho %', v_name;
                        CONTINUE;
                    END IF;


                    -- 1) Tạo bản ghi savedview
                    INSERT INTO documents_savedview(
                        name,
                        show_on_dashboard,
                        show_in_sidebar,
                        sort_field,
                        sort_reverse,
                        owner_id,
                        display_mode,
                        display_fields
                    )
                    VALUES (
                        v_name,                      -- name
                        TRUE,                        -- show_on_dashboard
                        TRUE,                        -- show_in_sidebar
                        'added',                     -- sort_field
                        TRUE,                        -- sort_reverse
                        NEW.id,                      -- owner_id
                        'smallCards',                -- display_mode
                        '["added","title","tag","custom_field_1"]'::jsonb
                    )
                    RETURNING id INTO v_savedview_id;


                    -- 2) Tạo filter rule tương ứng
                    INSERT INTO documents_savedviewfilterrule (
                        rule_type,
                        value,
                        saved_view_id
                    )
                    VALUES (
                        28,                 -- rule_type
                        v_doc_type_id,      -- value (id documenttype)
                        v_savedview_id
                    );

                END LOOP;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS after_user_created_create_savedviews ON auth_user;

            CREATE TRIGGER after_user_created_create_savedviews
            AFTER INSERT ON auth_user
            FOR EACH ROW
            EXECUTE FUNCTION create_default_savedviews_for_user();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS after_user_created_create_savedviews ON auth_user;
            DROP FUNCTION IF EXISTS create_default_savedviews_for_user();
            """
        )
    ]
